### ISSUE TITLE
بروزرسانی

### ISSUE THREAD

**Issue by sajaddp** [RTLer/zarinpal-composer-library#11]
سلام
شاید بد نباشه این پکیج رو بروز کنید..
برای مثال توابع استاتیک نیستند ولی در readme 
استاتیک استفاده شده!

**Comment by Saeed-Pooyanfar** [comment]
سلام
پکیج زیر رو میتونید چک کنید:
https://github.com/Saeed-Pooyanfar/zarinpal-laravel
بدون مشکل کار میکنه

**Comment by RTLer** [comment]
the one you need to use is https://github.com/RTLer/zarinpal-composer-library#usage
not laravel part
