### ISSUE TITLE
error code 101 should not result in completely failure

### ISSUE THREAD

**Issue by benjaco** [RTLer/zarinpal-composer-library#13]
When I get error 101, then I only got a status error and the error code, but the API is returning the RefID as well, but the rest driver is just dropping this field.

here is a possible solution for the rest driver

    /**
     * verify driver.
     *
     * @param $inputs
     *
     * @return array
     */
    public function verify($inputs)
    {
        $result = $this->restCall('PaymentVerification.json', $inputs);
        
        if ($result['Status'] == 100) {
            return ['Status' => 'success', 'RefID' => $result['RefID']];
        } elseif ($result['Status'] == 101) {
            // status error for backwards compebility, should meybe be changed to success
            return ['Status' => 'error', 'error' => $result['Status'], 'RefID' => $result['RefID']];
        } else {
            return ['Status' => 'error', 'error' => $result['Status']];
        }
    }

**Comment by hadimansouri** [comment]
I have two pull request on one of forks of this project. I agree with benjaco. Status code 101 should be considered as success.

https://github.com/ZarinPal-Lab/Composer-Library/pull/4

**Comment by RTLer** [comment]
this package  no longer include soap driver you can write your own implementing `\Zarinpal\Drivers\DriverInterface` and use as driver
