### ISSUE TITLE
Redirection bug

### ISSUE THREAD

**Issue by mohamadnorouzi20** [RTLer/zarinpal-composer-library#17]
Zarinpal::redirect function does not take sandbox flag into account and always redirect to "https://www.zarinpal.com/pg/StartPay/" instead of "https://sandbox.zarinpal.com/pg/StartPay".

I think you should add a getter for $baseUrl in DriverInterface and use that getter in Zarinpal::request instead of the hardcoded string.

**Comment by RTLer** [comment]
it's fixed now 
thx @mohamadnorouzi20
