### ISSUE TITLE
101 response on verify method

### ISSUE THREAD

**Issue by mohamadnorouzi20** [RTLer/zarinpal-composer-library#18]
It's sometimes needed to get the reference key on verify method even though the verify has been done before. currently the verify method only returns 101 error and no reference key. you could add a flag to the Zarinpal::verify and also DriverInterface::verify method to do the same thing for 101 response as if it is 100.

**Comment by RTLer** [comment]
in version 1.3.2  it pass `"verified_before"` in status if it gets "101"
