### ISSUE TITLE
logical error in shared payoff

### ISSUE THREAD

**Issue by SEPIMAGNA** [RTLer/zarinpal-composer-library#25]
`
$results = Zarinpal::request(
    "example.com/testVerify.php",          //required
    1000,                                  //required
    'testing',                             //required
    'me@example.com',                      //optional
    '09000000000',                         //optional
    json_encode([                          //optional
        "Wages" => [
            "zp.1.1" => [
                "Amount" => 120,
                "Description" => "part 1"
            ],
            "zp.2.5" => [
                "Amount" => 60,
                "Description" => "part 2"
            ]
        ]
    ])
);
`
Last argument must not be json encoded...It does not give error when you do and you can complete the transaction any way but when it is done...zarinpal does not share the amount...rewrite documents both in zarinpal and your package...thanks
@aminkt

**Comment by amiri27** [comment]
Sorry for this delay.. That would be fixed in pull request #30

**Comment by SEPIMAGNA** [comment]
@amiri27 Thanks.
