### ISSUE TITLE
Add a redirectUrl method to Zarinpal Class

### ISSUE THREAD

**Issue by mohamadnorouzi20** [RTLer/zarinpal-composer-library#27]
I need to send the redirect url to my javascript code and do the redirection on client side, but the redirect method does it on the server.
Please add a redirectUrl method that merely returns the url and doesnt do the redirection.

**Comment by amiri27** [comment]
@mohamadnorouzi20 good idea.. Can you propose a pull request for this?

**Comment by hoomanna** [comment]
#29 merged
